GET http://localhost:8080/timeline/cuzkop HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/tweets/cuzkop HTTP/1.1
Content-Type: application/json

{
    "text": "hello world"
}

###
DELETE http://localhost:8080/tweets/cuzkop HTTP/1.1
Content-Type: application/json

{
    "id": 22
}

###
POST http://localhost:8080/favorites/cuzkop HTTP/1.1
Content-Type: application/json

{
    "tweet_id": 1
}

###
DELETE http://localhost:8080/favorites/cuzkop HTTP/1.1
Content-Type: application/json

{
    "tweet_id": 1
}

###

POST http://localhost:8080/tweets/cuzkop/21 HTTP/1.1
Content-Type: application/json

{
    "text": "hello comment2"
}
